Workshop
CodersLab-core/Programujdziewczyno pull request #1
Opened 2017-08-27 14:18 UTC by joannabochynska

Instrukcje wykonywania poszczególnych zadań

2017-08-28 15:56 UTC, JacekTchorzewski-CL requested changes
Sprawdzone części 1 i 2. jutro siądę do dalszego sprawdzania.

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 1/README.md
> +3. Sprawdź, czy plik działa np. przez wpisanie w nim `console.log('działa')`. Ta wiadomość powinna wyświetlić się w konsoli po wejściu na stronę.
Brak średnika w przykładzie kodu.

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 1/README.md
> +##Dropdown menu
Brakuje spacji po ## - przez to nie wyświetla się dobrze.

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 1/README.md
> +Naszym celem jest sprawienie, by po najechaniu kursorem myszy na sekcję `Materiały do nauki` pojawiało się dodatkowe menu.
To trzeba lepiej opisać. Jak pierwszy raz czytałem zdanie to nie rozumiałem czy to ma być na sekcji strony czy na części menu. ja bym proponował taki opis:
"Naszym celem jest sprawienie, by po najechaniu kursorem myszy na cześć menu górnego z napisem `Materiały do nauki` pojawiało się dodatkowe rozwijane menu."

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 1/README.md
> +1. Spójrz na kod HTML i znajdź w nim element, w którym znajduje się dodatkowe menu oraz element listy, na który trzeba najechać myszką, by ta dodatkowa sekcja się pokazała. Następnie zapisz oba eleme
Totaj bym dopisał im hinta żeby pamiętać o kropce przy klasach a o # przy id - inaczej może być dużo problemów.

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 1/README.md
> +4. W JS możemy wpływać na wygląd elementów przez ich atrybut `style`. Na początku kodu spróbuj zrobić `console.log`, który pokaże Ci atrybut `style` dla zmiennej z dodatkowym menu. Możesz zobaczyć te
Kursanci nie wiedzą co to atrybuty.

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 1/README.md
> +element.style.display = 'block'
Średnik na końcu

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 1/README.md
> +## Instrukcja
Powiększył bym ten element

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 2/README.md
> +    console.log(buttons[0].previousElementSibling);
Pojawia się nam magiczna zmienna ```buttons``` której nigdy wcześniej nie było - jeżeli chcesz się do niej odwoływać to w poprzednim punkcie musisz dodać snippet z tworzeniem tej zmiennej i wrzuceniem do niej wyszukanych guzików.

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 2/README.md
> +```
Cały punkt 8 jest błędny. nastawienie `display` na `none` nie powoduje że `nexElementSiblig` zwraca nam null. Popatrz tutaj: https://codepen.io/CodersLab/pen/PKyOrx

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 2/README.md
> +    function showHide(): {
Dwukropek przed nawiasem klamrowym - to nie będzie działać.

2017-08-28 15:56 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 2/README.md
> +```
NIe wiem czy to im nie zamiesza (wkładanie do funkcji kodu zmieniającego widoczność). Nie wiem czy nie zostawiłbym to że na i-tym elemencie tablicy dodają po prostu event listenery.

2017-08-29 08:17 UTC, JacekTchorzewski-CL requested changes
Przeczytane i sprawdzone do końca. Kilka uwag:
1. Wydaje mi się że zadanie 6 może okazać się za trudne, ale nie wiem jaki jest dokładnie poziom dziewczyn i zaangażowanie - więc mogę się mylić.

2. Chcesz wprawdzić im dużo tematów, co samo w sobie jest fajne, ale ja bym się ograniczył do pewnych prostych rozwiązań. Np. wprowadzenie IIFE to duża przesada - nie wniesie im wiedzy żeby to zrozumieć (wiązanie kontekstu, itp) a może tylko namieszać.

3. Zmieniłbym trochę strukturę zadań na coś takiego:
    1. Zadanie 1 - robione z prowadzącą - może być opisane dokładnie tak jak jest,
    2. Zadanie 2 - Powinno być lepiej opisane - tutaj wręcz można w treści zadania wpisywać komendy które mają być przepisane do rozwiązania. Chodiz o to żeby na początku w łatwy sposób coś się udało i żeby się nie zniechęciły.
    3. Zadanie 3 - Tutaj wypisywać kawałki kodu tylko z nowymi rzeczami - przy rzeczach które były np w zadaniu 1 lub 2 odsyłać do odpowiednich punktów.
    4. Reszta zadań tak jak jest do tej pory.

2017-08-29 08:17 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 3/README.md
> +Naszym celem jest zaznaczenie dolnej krawędzi menu, gdy użytkownik przesuwa stronę na dół. Po włączeniu strony menu nie ma wyraźnej dolnej granicy i zlewa się z jasnym tłem przy scrollowaniu.
Dla mnie ten opis jest niezrozumiały.

2017-08-29 08:17 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 4/README.md
> +3. W poprzednim zadaniu nasłuchiwaliśmy na `scroll` dla okna, czyli `window`. Okno w JS ma wiele właściwiości, które możemy wykorzystać. Jedną z nich jest `scroll`. Pozwala ona na przeniesienie do ko
Ja bym tutaj nie wspominał o poprzednim zadaniu i evencie `scroll`. Event ten jest czymś innym niż metoda `scroll` i może im się to mieszać.

2017-08-29 08:17 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 5/README.md
> +    for(var i = 0; i <= dots.length; i++) {
To jest źle - i powinno być miejsce niż długość listy a nie mniejsze lub równe.

2017-08-29 08:17 UTC, JacekTchorzewski-CL commented on workshop/Zadanie 5/README.md
> +13. Efektem naszej pracy są trzy funkcje przypisane do trzech różnych kropek. Kod działa tak, jak powinien, ale powtarzamy jego część. Dlatego teraz przypiszemy funkcję do wszystkich kropek za jednym
Uważam że nie trzeba wprwadzać im IFIFE - mało kto to zrozumie na tym poziomie.

2017-08-29 21:13 UTC, joannaotmianowska reviewed
Dziękuję bardzo za sprawdzenie! Wprowadziłam wymagane zmiany:

Ad. 1 - Specjalnie zrobiłam to 6 zadanie trudniejsze i podzielone na poszczególne stopnie trudności, bo nie wiem niestety jaki poziom będa miały dziewczyny. Dla osób początkujących tylko pierwszy krok będzie ok, a jak ktoś będzie chciał sie pobawić dalej, to będzie miał do tego materiał. Dodatkowo chciałam coś zostawić dziewczynom w ramach pracy domowej i pewnie docelowo to będzie to zadanie.

Ad 2 Usunęłam IIFE, bo też właśnie miałam wątpliwości, czy to nie jest za dużo. Zostawiłam za to przekazywanie funkcji jako callback, tylko dokładniej to opisałam.

Ad 3 Zmieniłam struktrurę zgodnie ze wskazówkami. W drugim zadaniu są fragmenty kodu, które można przekleić do edytora. W trzecim zadaniu już tylko to, czego nie było wcześniej.

Daj proszę znać, czy jeszcze coś jest do poprawki :)

2017-08-29 21:13 UTC, joannaotmianowska commented on workshop/Zadanie 2/README.md
> +```
Później chciałam wykorzystać przypisywanie poszczególnych funkcji (głównie w tym zadaniu z listą). Wydaje mi się, że można po prostu powiedzieć, że to są dwa sposoby. Może akurat komuś któryś się wyda bardziej zrozumiały na pierwszy rzut oka. Mogę oczywiście to wyrzucić i pozmieniać w kodzie, ale nie uważam, żeby to bardzo mieszało :)

2017-08-29 21:13 UTC, joannaotmianowska commented on workshop/Zadanie 5/README.md
> +13. Efektem naszej pracy są trzy funkcje przypisane do trzech różnych kropek. Kod działa tak, jak powinien, ale powtarzamy jego część. Dlatego teraz przypiszemy funkcję do wszystkich kropek za jednym
Wyrzuciłam ten fragment na razie. Sama się też właśnie zastanawiałam, czy IIFE ma sens. Ale zostanę przy trzech funkcjach dla trzech kropek w takim razie.

2017-08-30 12:55 UTC, JacekTchorzewski-CL approved these changes
Dla mnie teraz jest ok.

2017-08-30 12:55 UTC, merged